trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  phpVersion: '8.1'
  deployHost: '10.0.0.1'
  deployUser: 'user'
  deployPath: '/var/www/app'

steps:
  - task: UsePhpVersion@1
    inputs:
      version: $(phpVersion)

  - script: |
      curl -sS https://getcomposer.org/installer | php
      php composer.phar install --no-dev --optimize-autoloader
    displayName: 'Instalar dependências com Composer'

  - script: |
      ./vendor/bin/phpunit --testdox
    displayName: 'Executar Testes Unitários'

  - script: |
      zip -r app.zip . -x "*.git*" -x "tests/*"
    displayName: 'Criar pacote de deploy'

## etapa com ssh para adicionar no host efemero, nao 
  - script: |
    echo "$(SSH_PRIVATE_KEY)" > /tmp/id_rsa
    chmod 600 /tmp/id_rsa
  displayName: 'Carregar chave privada SSH'

  - script: |
      scp -o StrictHostKeyChecking=no -i /tmp/id_rsa -r $(System.DefaultWorkingDirectory) $(deployUser)@$(deployHost):$(deployPath)
    displayName: 'Transferir arquivos para o servidor'

  - script: |
      ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa $(deployUser)@$(deployHost) "cd $(deployPath) && unzip -o app.zip && rm app.zip"
    displayName: 'Executar comandos no servidor'



